LampShade/ServiceHost/Areas/Administration/Pages/Comments/Index.cshtml.cs
using System.Collections.Generic;
using CommentManagement.Application.Contract.A.Comment;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Areas.Administration.Pages.Comments

{
    public class IndexModel : PageModel
    {
        [TempData] public string Message { get; set; }
        public List<CommentViewModel> Comments;
        public CommentSearchModel SearchModel;

        private readonly ICommentApplication _comment;

        public IndexModel(ICommentApplication comment)
        {
            _comment = comment;
        }


        public void OnGet(CommentSearchModel searchModel)
        {
            Comments = _comment.Search(searchModel);
        }

        public RedirectToPageResult OnGetConfirm(long id)
        {
            var result= _comment.Confirm(id);
            if (result.IsSucceeded)
                return RedirectToPage("./Index");

            Message = result.Message;
            return RedirectToPage("./Index");
        }

        public RedirectToPageResult OnGetCancel(long id)
        {
           var result= _comment.Cancel(id);
           if (result.IsSucceeded)
               return RedirectToPage("./Index");

           Message = result.Message;
           return RedirectToPage("./Index");
        }
    }
}

LampShade/ServiceHost/Areas/Administration/Pages/Shop/Comments/Index.cshtml.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ShopManagement.Application.Contract.A.Comment;

namespace ServiceHost.Areas.Administration.Pages.Shop.Comments
{
    public class IndexModel : PageModel
    {
        [TempData] public string Message { get; set; }
        public List<CommentViewModel> Comments;
        public CommentSearchModel SearchModel;

        private readonly ICommentApplication _comment;

        public IndexModel(ICommentApplication comment)
        {
            _comment = comment;
        }


        public void OnGet(CommentSearchModel searchModel)
        {
            Comments = _comment.Search(searchModel);
        }

        public RedirectToPageResult OnGetConfirm(long id)
        {
            var result= _comment.Confirm(id);
            if (result.IsSucceeded)
                return RedirectToPage("./Index");

            Message = result.Message;
            return RedirectToPage("./Index");
        }

        public RedirectToPageResult OnGetCancel(long id)
        {
           var result= _comment.Cancel(id);
           if (result.IsSucceeded)
               return RedirectToPage("./Index");

           Message = result.Message;
           return RedirectToPage("./Index");
        }
    }
}

LampShade/ServiceHost/Areas/Administration/Pages/Comments/Index.cshtml
@page
@using CommentManagement.Infrastructure.EFCore
@model ServiceHost.Areas.Administration.Pages.Comments.IndexModel
@{
}

@{
    Layout = "Shared/_AdminLayout";
    ViewData["title"] = "مدیریت کامنت ها";
}

<div class="row">
    <div class="col-sm-12">
        <h4 class="page-title pull-right">@ViewData["title"]</h4>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">جستجو در کامنت ها</h3>
            </div>
            <div class="panel-body">
                <form class="form-inline" role="form" method="get">
                    <div class="form-group">
                        <label class="sr-only" asp-for="SearchModel.Name"></label>
                        <input class="form-control" asp-for="SearchModel.Name" placeholder="نام کامنت">
                    </div>
                    <div class="form-group">
                        <label class="sr-only" asp-for="SearchModel.Email"></label>
                        <input class="form-control" asp-for="SearchModel.Email" placeholder="ایمیل">
                    </div>
                    <button type="submit" class="btn btn-success waves-effect waves-light m-l-10">جستجو</button>
                    <a class="btn btn-primary waves-effect waves-light m-l-10" asp-page="./Index">مشاهده همه</a>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">لیست کامنت ها </h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <table id="datatable" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>نام</th>
                                    <th>ایمیل</th>
                                    <th>وضعیت</th>
                                    <th>پیام</th>
                                    <th>نوع</th>
                                    <th>تاریخ </th>
                                    <th>عملیات</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.Comments)
                                {
                                    <tr>
                                        <td>@item.Id</td>
                                        <td>@item.Name</td>
                                        <td>@item.Email</td>
                                        <td class="text-center">
                                            @if (!item.IsCanceled && !item.IsConfirmed)
                                            {
                                                <i class="fa fa-eye fa-2x text-info"></i>
                                            }
                                            else if (item.IsCanceled)
                                            {
                                                <i class="fa fa-remove fa-2x text-danger"></i>
                                            }
                                            else
                                            {
                                                <i class="fa fa-check fa-2x text-success"></i>
                                            }
                                        </td>
                                        <td>@item.Description</td>
                                        @if (@item.Type == CommentType.Product)
                                        {
                                            <td>محصولات</td>
                                        }
                                        @if (@item.Type == CommentType.Article)
                                        {
                                            <td>مقالات</td>
                                        }
                                        
                                        <td>@item.CommentDate</td>
                                        <td>
                                            <a class="btn btn-danger btn-custom waves-effect waves-light m-b-5" asp-page="./Index" asp-page-handler="Cancel"
                                               asp-route-id="@item.Id">کنسل</a>
                                            @if (!item.IsConfirmed)
                                            {

                                                <a class="btn btn-success btn-custom waves-effect waves-light m-b-5" asp-page="./Index" asp-page-handler="Confirm"
                                                   asp-route-id="@item.Id">تایید</a>
                                            }
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
<script src="~/adminTheme/assets/datatables/jquery.dataTables.min.js"></script>
<script src="~/adminTheme/assets/datatables/dataTables.bootstrap.js"></script>

<script type="text/javascript">
    $(document).ready(function () {
        $('#datatable').dataTable();
    });
</script>
}