LampShade/ServiceHost/ViewComponents/FooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace ServiceHost.ViewComponents
{
    public class FooterViewComponent : ViewComponent
    {

        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

LampShade/ServiceHost/ViewComponents/MenuViewComponent.cs
using _01_LampShadeQuery;
using _01_LampShadeQuery.Contract.ArticleCategory;
using _01_LampShadeQuery.Contract.ProductCategory;
using Microsoft.AspNetCore.Mvc;

namespace ServiceHost.ViewComponents
{
    public class MenuViewComponent : ViewComponent
    {
        private readonly IProductCategoryQuery _productCategory;
        private readonly IArticleCategoryQuery _articleCategory;
        public MenuViewComponent(IProductCategoryQuery productCategory, IArticleCategoryQuery articleCategory)
        {
            _productCategory = productCategory;
            _articleCategory = articleCategory;
        }

        public IViewComponentResult Invoke()
        {
            var result = new MenuModel
            {
                ArticleCategories = _articleCategory.GetArticleCategories(),
                ProductCategories = _productCategory.GetProductCategoryQueries()
            };
            return View(result);
        }
    }
}

LampShade/ServiceHost/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    @if (ViewData["Title"] != null)
    {
        <title>@ViewData["Title"]-فروشگاه لوازم خانگی</title>
    }
    else
    {
        <title>فروشگاه لوازم خانگی</title>
    }
    <meta name="keywords" content="@ViewData["Keywords"]" />
    <meta name="description" content="@ViewData["metaDescription"]" />

    <link href="~/Theme/assets/css/vendors.css" rel="stylesheet">
    <link href="~/Theme/assets/css/style.css" rel="stylesheet">
    <link href="~/Theme/assets/css/Custom.css" rel="stylesheet">
    @await RenderSectionAsync("Css", false)
</head>

<body>


    @await Component.InvokeAsync("Menu");

    @RenderBody()

    @await Component.InvokeAsync("Footer");


    <div class="search-overlay" id="search-overlay">
        <a href="javascript:void(0)" class="close-search-overlay" id="close-search-overlay">
            <i class="ion-ios-close-empty"></i>
        </a>
        <div class="search-form">
            <form method="get" asp-page="/Search">
                <input type="search" name="value" id="value" placeholder="جستجو در داخل فروشگاه...">
                <button type="submit">
                    <i class="ion-android-search"></i>
                </button>
            </form>
        </div>
    </div>
    <div id="scroll-top">
        <span>بورو بالا</span><i class="ion-chevron-right"></i><i class="ion-chevron-right"></i>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/Theme/assets/js/vendors.js"></script>
    <script src="~/Theme/assets/js/active.js"></script>
    <script src="~/Theme/assets/js/plugins.js"></script>
    <script src="~/Theme/assets/js/custom.js"></script>
    @await RenderSectionAsync("Scripts", false)
    <script>
        $(document).ready(function() {
            updateCart();
        });
    </script>
</body>
</html>