LampShade/ServiceHost/Areas/Administration/Pages/Accounts/Role/Create.cshtml.cs
using AccountManagement.Application.Contracts.AC.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Areas.Administration.Pages.Accounts.Role
{
    public class CreateModel : PageModel
    {
        public CreateRole Command;
        private readonly IRoleApplication _roleApplication;

        public CreateModel(IRoleApplication roleApplication)
        {
            _roleApplication = roleApplication;
        }

        public void OnGet()
        {
            var command = new CreateRole();
        }

        public RedirectToPageResult OnPost(CreateRole command)
        {
            var result = _roleApplication.Create(command);
           return RedirectToPage("Index");
        }
    }
}

LampShade/ServiceHost/Areas/Administration/Pages/Accounts/Role/Edit.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using _0_Framework.Repository;
using AccountManagement.Application.Contracts.AC.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Accounts.Role
{
    public class EditModel : PageModel
    {
        public EditRole Command;
        public List<SelectListItem> Permissions =new List<SelectListItem>();
        private readonly IRoleApplication _roleApplication;
        private readonly IEnumerable<IPermissionExposer> _permissionsExposers;

        public EditModel(IRoleApplication roleApplication, IEnumerable<IPermissionExposer> permissionsExposers)
        {
            _roleApplication = roleApplication;
            _permissionsExposers = permissionsExposers;
        }

        public void OnGet(long id)
        {
            Command = _roleApplication.GetDetails(id);
            var permissions = new List<PermissionDto>();
            foreach (var exposer in _permissionsExposers)
            {
                var exposedPermissions = exposer.Expose();
                foreach (var (key, value) in exposedPermissions)
                {
                    permissions.AddRange(value);
                    var group = new SelectListGroup
                    {
                        Name = key
                    };
                    foreach (var permission in value)
                    {
                        var item = new SelectListItem(permission.Name, permission.Code.ToString())
                        {
                            Group = group
                        };
                        if (Command.MappedPermissions.Any(x => x.Code == permission.Code))
                            item.Selected = true;

                        Permissions.Add(item);

                    }
                }
            }
        }

        public RedirectToPageResult OnPost(EditRole command)
        {
            var result = _roleApplication.Edit(command);
            return RedirectToPage("Index");
        }
    }
}

LampShade/ServiceHost/Areas/Administration/Pages/Blog/Articles/Create.cshtml.cs
using BlogManagement.Application.Contract.AC.Article;
using BlogManagement.Application.Contract.AC.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Blog.Articles
{
    public class CreateModel : PageModel
    {
        public CreateArticle Command;
        public SelectList ArticleCategories;
        private readonly IArticleCategoryApplication _categoryApplication;
        private readonly IArticleApplication _articleApplication;

        public CreateModel(IArticleCategoryApplication categoryApplication, IArticleApplication articleApplication)
        {
            _categoryApplication = categoryApplication;
            _articleApplication = articleApplication;
        }

        public void OnGet()
        {
            ArticleCategories = new SelectList(_categoryApplication.GetArticleCategories(), "Id", "Name");
        }

        public RedirectToPageResult OnPost(CreateArticle command)
        {
            var result = _articleApplication.Create(command);
            return RedirectToPage("./Index");
        }
    }
}

LampShade/ServiceHost/Areas/Administration/Pages/Blog/Articles/Edit.cshtml.cs
using BlogManagement.Application.Contract.AC.Article;
using BlogManagement.Application.Contract.AC.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Blog.Articles
{
    public class EditModel : PageModel
    {
        public EditArticle Command;
        public SelectList ArticleCategories;
        private readonly IArticleCategoryApplication _categoryApplication;
        private readonly IArticleApplication _articleApplication;

        public EditModel(IArticleCategoryApplication categoryApplication, IArticleApplication articleApplication)
        {
            _categoryApplication = categoryApplication;
            _articleApplication = articleApplication;
        }

        public void OnGet(long id)
        {
            Command = _articleApplication.GetDetails(id);
            ArticleCategories = new SelectList(_categoryApplication.GetArticleCategories(), "Id", "Name");
        }

        public RedirectToPageResult OnPost(EditArticle command)
        {
            var result = _articleApplication.Edit(command);
            return RedirectToPage("./Index");
        }
    }
}

LampShade/ServiceHost/Areas/Administration/Pages/Shop/Comments/Index.cshtml.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ShopManagement.Application.Contract.A.Comment;

namespace ServiceHost.Areas.Administration.Pages.Shop.Comments
{
    public class IndexModel : PageModel
    {
        [TempData] public string Message { get; set; }
        public List<CommentViewModel> Comments;
        public CommentSearchModel SearchModel;

        private readonly ICommentApplication _comment;

        public IndexModel(ICommentApplication comment)
        {
            _comment = comment;
        }


        public void OnGet(CommentSearchModel searchModel)
        {
            Comments = _comment.Search(searchModel);
        }

        public RedirectToPageResult OnGetConfirm(long id)
        {
            var result= _comment.Confirm(id);
            if (result.IsSucceeded)
                return RedirectToPage("./Index");

            Message = result.Message;
            return RedirectToPage("./Index");
        }

        public RedirectToPageResult OnGetCancel(long id)
        {
           var result= _comment.Cancel(id);
           if (result.IsSucceeded)
               return RedirectToPage("./Index");

           Message = result.Message;
           return RedirectToPage("./Index");
        }
    }
}

LampShade/ServiceHost/Areas/Administration/Pages/Shop/Orders/Index.cshtml.cs
using System.Collections.Generic;
using AccountManagement.Application.Contracts.AC.Account;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShopManagement.Application.Contract.Order;

namespace ServiceHost.Areas.Administration.Pages.Shop.Orders
{
    public class IndexModel : PageModel
    {
        public List<OrderViewModel> Orders;
        public OrderSearchModel SearchModel;
        public SelectList Accounts;
        private readonly IOrderApplication _orderApplication;
        private readonly IAccountApplication _accountApplication;

        public IndexModel(IOrderApplication orderApplication, IAccountApplication accountApplication)
        {
            _orderApplication = orderApplication;
            _accountApplication = accountApplication;
        }

        public void OnGet(OrderSearchModel searchModel)
        {
            Accounts = new SelectList(_accountApplication.GetAccounts(), "Id", "FullName");
            Orders = _orderApplication.Search(searchModel);
        }

        public RedirectToPageResult OnGetConfirm(long id)
        {
            _orderApplication.PaymentSucceeded(id, 0);
            return RedirectToPage("Index");
        }

        public RedirectToPageResult OnGetCancel(long id)
        {
            _orderApplication.Cancel(id);
            return RedirectToPage("Index");
        }

        public PartialViewResult OnGetItems(long id)
        {
            var items = _orderApplication.GetItemsBy(id);
            return Partial("Items", items);
        }

    }
}

LampShade/ServiceHost/Areas/Administration/Pages/Shop/ProductCategories/Index.cshtml.cs
using System.Collections.Generic;
using _0_Framework.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ShopManagement.Application.Contract.ProductCategory;
using ShopManagement.Configuration.Permissions;

namespace ServiceHost.Areas.Administration.Pages.Shop.ProductCategories
{
    public class IndexModel : PageModel
    {
        public List<ProductCategoryViewModel> ProductCategories;
        public ProductCategorySearchModel SearchModel;
        private readonly IProductCategoryApplication _categoryApplication;

        public IndexModel(IProductCategoryApplication categoryApplication)
        {
            _categoryApplication = categoryApplication;
        }

        [NeedsPermission(ShopPermissions.ListProductCategories)]
        public void OnGet(ProductCategorySearchModel searchModel)
        {
            ProductCategories = _categoryApplication.Search(searchModel);
        }

        public PartialViewResult OnGetCreate()
        {
            return Partial("./Create", new CreateProductCategory());
        }

        [NeedsPermission(ShopPermissions.CreateProductCategory)]
        public JsonResult OnPostCreate(CreateProductCategory command)
        {
            var result = _categoryApplication.Create(command);
            return new JsonResult(result);
        }

        public PartialViewResult OnGetEdit(long id)
        {
            var editProductCategory = _categoryApplication.GetDetails(id);
            return Partial("Edit", editProductCategory);
        }

        [NeedsPermission(ShopPermissions.EditProductCategory)]
        public JsonResult OnPostEdit(EditProductCategory command)
        {
            var result = _categoryApplication.Edit(command);
            return new JsonResult(result);
        }
    }
}

LampShade/ServiceHost/Areas/Administration/Pages/Shop/ProductPictures/Index.cshtml.cs
using System.Collections.Generic;
using _0_Framework.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShopManagement.Application.Contract.A.Product;
using ShopManagement.Application.Contract.A.ProductPicture;
using ShopManagement.Configuration.Permissions;

namespace ServiceHost.Areas.Administration.Pages.Shop.ProductPictures
{
    public class IndexModel : PageModel
    {
        [TempData] public string Message { get; set; }
        public List<ProductPictureViewModel> ProductPictures;
        public ProductPictureSearchModel SearchModel;
        public SelectList Products;

        private readonly IProductApplication _productApplication;
        private readonly IProductPictureApplication _productPictureApplication;
        public IndexModel(IProductApplication productApplication, IProductPictureApplication productPictureApplication)
        {
            _productApplication = productApplication;
            _productPictureApplication = productPictureApplication;
        }

        [NeedsPermission(ShopPermissions.ListProductCategories)]
        public void OnGet(ProductPictureSearchModel searchModel)
        {
            Products = new SelectList(_productApplication.GetProducts(),"Id","Name");
            ProductPictures = _productPictureApplication.Search(searchModel);
        }

        public PartialViewResult OnGetCreate()
        {
            var command = new CreateProductPicture
            {
                Products = _productApplication.GetProducts()
            };
            return Partial("./Create", command);
        }

        [NeedsPermission(ShopPermissions.CreateProductCategory)]
        public JsonResult OnPostCreate(CreateProductPicture command)
        {
            var result = _productPictureApplication.Create(command);
            return new JsonResult(result);
        }

        public PartialViewResult OnGetEdit(long id)
        {
            var editProductPicture = _productPictureApplication.GetDetails(id);
            editProductPicture.Products = _productApplication.GetProducts();
            return Partial("Edit", editProductPicture);
        }

        [NeedsPermission(ShopPermissions.EditProductCategory)]
        public JsonResult OnPostEdit(EditProductPicture command)
        {
            var result = _productPictureApplication.Edit(command);
            return new JsonResult(result);
        }

        public RedirectToPageResult OnGetRestore(long id)
        {
            var result= _productPictureApplication.Restore(id);
            if (result.IsSucceeded)
                return RedirectToPage("./Index");

            Message = result.Message;
            return RedirectToPage("./Index");
        }

        public RedirectToPageResult OnGetRemove(long id)
        {
           var result= _productPictureApplication.Remove(id);
           if (result.IsSucceeded)
               return RedirectToPage("./Index");

           Message = result.Message;
           return RedirectToPage("./Index");
        }
    }
}

LampShade/ServiceHost/Areas/Administration/Pages/Shop/Products/Index.cshtml.cs
using System.Collections.Generic;
using _0_Framework.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShopManagement.Application.Contract.A.Product;
using ShopManagement.Application.Contract.ProductCategory;
using ShopManagement.Configuration.Permissions;

namespace ServiceHost.Areas.Administration.Pages.Shop.Products
{
    public class IndexModel : PageModel
    {
        [TempData] public string Message { get; set; }
        public List<ProductViewModel> Products;
        public ProductSearchModel SearchModel;
        public SelectList ProductCategories;
        private readonly IProductApplication _productApplication;
        private readonly IProductCategoryApplication _productCategoryApplication;

        public IndexModel(IProductApplication productApplication, IProductCategoryApplication productCategoryApplication)
        {
            _productApplication = productApplication;
            _productCategoryApplication = productCategoryApplication;
        }

        [NeedsPermission(ShopPermissions.ListProducts)]
        public void OnGet(ProductSearchModel searchModel)
        {
            ProductCategories = new SelectList(_productCategoryApplication.GetProductCategories(), "Id", "Name");
            Products = _productApplication.Search(searchModel);
        }

        public PartialViewResult OnGetCreate()
        {
            var command = new CreateProduct
            {
                Products = _productCategoryApplication.GetProductCategories()
            };
            return Partial("./Create", command);
        }

        [NeedsPermission(ShopPermissions.CreateProduct)]
        public JsonResult OnPostCreate(CreateProduct command)
        {
            var result = _productApplication.Create(command);
            return new JsonResult(result);
        }

        public PartialViewResult OnGetEdit(long id)
        {
            var editProduct = _productApplication.GetDetails(id);
            editProduct.Products = _productCategoryApplication.GetProductCategories();
            return Partial("Edit", editProduct);
        }

        [NeedsPermission(ShopPermissions.EditProduct)]
        public JsonResult OnPostEdit(EditProduct command)
        {
            var result = _productApplication.Edit(command);
            return new JsonResult(result);
        }
    }
}

LampShade/ServiceHost/Areas/Administration/Pages/Shop/ProductPictures/Create.cshtml
@model ShopManagement.Application.Contract.A.ProductPicture.CreateProductPicture
@{
}
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ایجاد عکس محصول جدید</h4>
</div>

<form asp-page="./Index" asp-page-handler="Create"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label asp-for="ProductId" class="control-label">  محصول </label>
                        <select class="form-control" asp-for="ProductId" asp-items='new SelectList(Model.Products,"Id","Name")'>
                            <option value="0"> محصول...</option>
                        </select>
                        <span asp-validation-for="ProductId" class="error"></span>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="PictureUrl" class="control-label">عکس</label>
                    <input type="file" class="form-control" asp-for="PictureUrl" accept="image/*">
                    <span asp-validation-for="PictureUrl" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="PictureAlt" class="control-label">Alt</label>
                    <input type="text" class="form-control" asp-for="PictureAlt">
                    <span asp-validation-for="PictureAlt" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="PictureTitle" class="control-label">عنوان</label>
                    <input type="text" class="form-control" asp-for="PictureTitle">
                    <span asp-validation-for="PictureTitle" class="error"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ایجاد</button>
    </div>
</form>

LampShade/ServiceHost/Areas/Administration/Pages/Shop/ProductPictures/Edit.cshtml
@model ShopManagement.Application.Contract.A.ProductPicture.EditProductPicture
@{
}
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ویرایش عکس محصول:@Model.PictureAlt</h4>
</div>

<form asp-page="./Index" asp-page-handler="Edit"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label asp-for="ProductId" class="control-label">  محصول </label>
                        <select class="form-control" asp-for="ProductId" asp-items='new SelectList(Model.Products,"Id","Name")'>
                            <option value="0"> محصول...</option>
                        </select>
                        <span asp-validation-for="ProductId" class="error"></span>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="PictureUrl" class="control-label">عکس</label>
                    <input type="file" class="form-control" asp-for="PictureUrl" accept="image/*">
                    <span asp-validation-for="PictureUrl" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="PictureAlt" class="control-label">Alt</label>
                    <input type="text" class="form-control" asp-for="PictureAlt">
                    <span asp-validation-for="PictureAlt" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="PictureTitle" class="control-label">عنوان</label>
                    <input type="text" class="form-control" asp-for="PictureTitle">
                    <span asp-validation-for="PictureTitle" class="error"></span>
                </div>
            </div>
        </div>
        <input type="hidden" asp-for="Id" value="@Model.Id"/>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ویرایش</button>
    </div>
</form>

LampShade/ServiceHost/Areas/Administration/Pages/Shop/ProductPictures/Index.cshtml
@page
@model ServiceHost.Areas.Administration.Pages.Shop.ProductPictures.IndexModel
@{
}

@{
    Layout = "Shared/_AdminLayout";
    ViewData["title"] = "مدیریت عکس محصولات";
}

<div class="row">
    <div class="col-sm-12">
        <h4 class="page-title pull-right">@ViewData["title"]</h4>
        <p class="pull-left">
            <a class="btn btn-success btn-lg" href="#showmodal=@Url.Page("./Index", "Create")">ایجاد عکس محصول جدید</a>
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">جستجو در عکس محصولات</h3>
            </div>
            <div class="panel-body">
                <form class="form-inline" role="form" method="get">
                    <div class="form-group">
                        <label class="sr-only" asp-for="SearchModel.ProductId"></label>
                        <select class="form-control" asp-for="SearchModel.ProductId" asp-items="Model.Products">
                            <option value="0">محصول...</option>
                        </select>
                    </div>
                    <button type="submit" class="btn btn-success waves-effect waves-light m-l-10">جستجو</button>
                    <a class="btn btn-primary waves-effect waves-light m-l-10" asp-page="./Index">مشاهده همه</a>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row" id="ProductCategoriesDiv">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">لیست عکس محصولات</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <table id="datatable" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>عکس</th>
                                    <th>نام محصول</th>
                                    <th>وضعیت</th>
                                    <th>تاریخ تولید</th>
                                    <th>عملیات</th>
                                </tr>
                            </thead>
                            <tbody>
                           @foreach (var item in Model.ProductPictures)
                            {
                                <tr>
                                    <td>@item.Id</td>
                                    <td>
                                        <img src="~/ProductPictures/@item.PictureUrl" style="width: 70px; height: 70px" />
                                    </td>
                                    <td>@item.Product</td> 
                                    <td class="text-center">
                                        @if (!item.IsRemoved)
                                        {
                                            <i class="fa fa-check fa-2x text-success"></i>
                                        }
                                        else
                                        {
                                            <i class="fa fa-remove fa-2x text-danger"></i>

                                        }                                     
                                        
                                    </td>
                                    <td>@item.CreationDate</td>
                                    <td>
                                        <a class="btn btn-warning btn-custom waves-effect waves-light m-b-5" href="#showmodal=@Url.Page("./Index", "Edit" ,new {id=item.Id})">
                                            <i class="fa fa-edit"></i> ویرایش
                                        </a> 
                                        @if (!item.IsRemoved)
                                        {
                                            <a class="btn btn-danger btn-custom waves-effect waves-light m-b-5" asp-page="./Index" asp-page-handler="Remove" 
                                               asp-route-id="@item.Id">حذف</a>
                                        }
                                        else
                                        {
                                            <a class="btn btn-success btn-custom waves-effect waves-light m-b-5" asp-page="./Index" asp-page-handler="Restore" 
                                               asp-route-id="@item.Id">فعال سازی</a>
                                        }

                                    </td>
                                </tr>
                            }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/adminTheme/assets/datatables/jquery.dataTables.min.js"></script>
    <script src="~/adminTheme/assets/datatables/dataTables.bootstrap.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#datatable').dataTable();
        });
    </script>
}